version: "3.5"
services:
    company_test:
        image: company_test:latest
        container_name: company_test_project
        build: .
        command: python manage.py runserver 0.0.0.0:8080
        working_dir: /src
        volumes:
            - "../../:/src"
        networks:
            - net_company_test
        ports:
            - 8080:8080
        depends_on:
            - db

    db:
        image: postgres:9.6.company_test
        container_name: company_test_db
        build: ./pg
        volumes:
            - "dbdata:/var/lib/postgresql/data"
        networks:
            - net_company_test
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
volumes:
    dbdata:

networks:
    net_company_test:
        name: network_company_test